require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProfilePicturesController do

  # This should return the minimal set of attributes required to create a valid
  # ProfilePicture. As you add validations to ProfilePicture, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all profile_pictures as @profile_pictures" do
      profile_picture = ProfilePicture.create! valid_attributes
      get :index
      assigns(:profile_pictures).should eq([profile_picture])
    end
  end

  describe "GET show" do
    it "assigns the requested profile_picture as @profile_picture" do
      profile_picture = ProfilePicture.create! valid_attributes
      get :show, :id => profile_picture.id
      assigns(:profile_picture).should eq(profile_picture)
    end
  end

  describe "GET new" do
    it "assigns a new profile_picture as @profile_picture" do
      get :new
      assigns(:profile_picture).should be_a_new(ProfilePicture)
    end
  end

  describe "GET edit" do
    it "assigns the requested profile_picture as @profile_picture" do
      profile_picture = ProfilePicture.create! valid_attributes
      get :edit, :id => profile_picture.id
      assigns(:profile_picture).should eq(profile_picture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProfilePicture" do
        expect {
          post :create, :profile_picture => valid_attributes
        }.to change(ProfilePicture, :count).by(1)
      end

      it "assigns a newly created profile_picture as @profile_picture" do
        post :create, :profile_picture => valid_attributes
        assigns(:profile_picture).should be_a(ProfilePicture)
        assigns(:profile_picture).should be_persisted
      end

      it "redirects to the created profile_picture" do
        post :create, :profile_picture => valid_attributes
        response.should redirect_to(ProfilePicture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved profile_picture as @profile_picture" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProfilePicture.any_instance.stub(:save).and_return(false)
        post :create, :profile_picture => {}
        assigns(:profile_picture).should be_a_new(ProfilePicture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProfilePicture.any_instance.stub(:save).and_return(false)
        post :create, :profile_picture => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested profile_picture" do
        profile_picture = ProfilePicture.create! valid_attributes
        # Assuming there are no other profile_pictures in the database, this
        # specifies that the ProfilePicture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProfilePicture.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => profile_picture.id, :profile_picture => {'these' => 'params'}
      end

      it "assigns the requested profile_picture as @profile_picture" do
        profile_picture = ProfilePicture.create! valid_attributes
        put :update, :id => profile_picture.id, :profile_picture => valid_attributes
        assigns(:profile_picture).should eq(profile_picture)
      end

      it "redirects to the profile_picture" do
        profile_picture = ProfilePicture.create! valid_attributes
        put :update, :id => profile_picture.id, :profile_picture => valid_attributes
        response.should redirect_to(profile_picture)
      end
    end

    describe "with invalid params" do
      it "assigns the profile_picture as @profile_picture" do
        profile_picture = ProfilePicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfilePicture.any_instance.stub(:save).and_return(false)
        put :update, :id => profile_picture.id, :profile_picture => {}
        assigns(:profile_picture).should eq(profile_picture)
      end

      it "re-renders the 'edit' template" do
        profile_picture = ProfilePicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfilePicture.any_instance.stub(:save).and_return(false)
        put :update, :id => profile_picture.id, :profile_picture => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested profile_picture" do
      profile_picture = ProfilePicture.create! valid_attributes
      expect {
        delete :destroy, :id => profile_picture.id
      }.to change(ProfilePicture, :count).by(-1)
    end

    it "redirects to the profile_pictures list" do
      profile_picture = ProfilePicture.create! valid_attributes
      delete :destroy, :id => profile_picture.id
      response.should redirect_to(profile_pictures_url)
    end
  end

end
