require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TabSitesController do

  # This should return the minimal set of attributes required to create a valid
  # TabSite. As you add validations to TabSite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tab_sites as @tab_sites" do
      tab_site = TabSite.create! valid_attributes
      get :index
      assigns(:tab_sites).should eq([tab_site])
    end
  end

  describe "GET show" do
    it "assigns the requested tab_site as @tab_site" do
      tab_site = TabSite.create! valid_attributes
      get :show, :id => tab_site.id
      assigns(:tab_site).should eq(tab_site)
    end
  end

  describe "GET new" do
    it "assigns a new tab_site as @tab_site" do
      get :new
      assigns(:tab_site).should be_a_new(TabSite)
    end
  end

  describe "GET edit" do
    it "assigns the requested tab_site as @tab_site" do
      tab_site = TabSite.create! valid_attributes
      get :edit, :id => tab_site.id
      assigns(:tab_site).should eq(tab_site)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TabSite" do
        expect {
          post :create, :tab_site => valid_attributes
        }.to change(TabSite, :count).by(1)
      end

      it "assigns a newly created tab_site as @tab_site" do
        post :create, :tab_site => valid_attributes
        assigns(:tab_site).should be_a(TabSite)
        assigns(:tab_site).should be_persisted
      end

      it "redirects to the created tab_site" do
        post :create, :tab_site => valid_attributes
        response.should redirect_to(TabSite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tab_site as @tab_site" do
        # Trigger the behavior that occurs when invalid params are submitted
        TabSite.any_instance.stub(:save).and_return(false)
        post :create, :tab_site => {}
        assigns(:tab_site).should be_a_new(TabSite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TabSite.any_instance.stub(:save).and_return(false)
        post :create, :tab_site => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tab_site" do
        tab_site = TabSite.create! valid_attributes
        # Assuming there are no other tab_sites in the database, this
        # specifies that the TabSite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TabSite.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tab_site.id, :tab_site => {'these' => 'params'}
      end

      it "assigns the requested tab_site as @tab_site" do
        tab_site = TabSite.create! valid_attributes
        put :update, :id => tab_site.id, :tab_site => valid_attributes
        assigns(:tab_site).should eq(tab_site)
      end

      it "redirects to the tab_site" do
        tab_site = TabSite.create! valid_attributes
        put :update, :id => tab_site.id, :tab_site => valid_attributes
        response.should redirect_to(tab_site)
      end
    end

    describe "with invalid params" do
      it "assigns the tab_site as @tab_site" do
        tab_site = TabSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TabSite.any_instance.stub(:save).and_return(false)
        put :update, :id => tab_site.id, :tab_site => {}
        assigns(:tab_site).should eq(tab_site)
      end

      it "re-renders the 'edit' template" do
        tab_site = TabSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TabSite.any_instance.stub(:save).and_return(false)
        put :update, :id => tab_site.id, :tab_site => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tab_site" do
      tab_site = TabSite.create! valid_attributes
      expect {
        delete :destroy, :id => tab_site.id
      }.to change(TabSite, :count).by(-1)
    end

    it "redirects to the tab_sites list" do
      tab_site = TabSite.create! valid_attributes
      delete :destroy, :id => tab_site.id
      response.should redirect_to(tab_sites_url)
    end
  end

end
