email_settings:
  address: mail.cipher-tech.com
  port: 26
  domain: www.cipher-tech.com
  authentication: :login
  user_name: demo@cipher-tech.com
  password: 123cipher


notifier:
  from: demo@cipher-tech.com
